version: "3"

services:
  1c-serv:
    container_name: 1c-enterprice-roninore
    image: roninore/1csrv:1.0
    ports:
      - "1540:1540"
      - "1541:1541"
      - "1560:1591"
    environment:
      - SRV1CV8_KEYTAB: /opt/1cv8/x86_64/8.3.23.2040/usr1cv8.keytab
      - SRV1CV8_PORT: 1540
      - SRV1CV8_REGPORT: 1541
      - SRV1CV8_RANGE: 1560:1591
      - SRV1CV8_DEBUG: 
      - SRV1CV8_DATA: /home/usr1cv8/.1cv8/1C/1cv8
      - SRV1CV8_SECLEV: 0
      - SRV1CV8_PINGPERIOD: 1000
      - SRV1CV8_PINGTIMEOUT: 5000
    volumes:
      - "./1c_data:/home/usr1cv8/.1cv8/1C"
    networks:
      - 1c-ent

networks:
  1c-ent:
    external: true