version: "3"

services:
  postgres-1c:
    container_name: postgres-1c
    build:
      context: ..
      dockerfile: deployments/postgres/Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - "./postgres-data:/var/lib/pgpro/1c-15/data"
    networks:
      - 1c-ent

networks:
  1c-ent:
    external: true